services:
    frontend:
      container_name: three_experience
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:5173
      volumes:
        - ./src:/app/src
        - ./public:/app/public
      env_file:
        - ./.env